SELECT TOP (1000) [id]
      ,[name_fr]
      ,[name_en]
      ,[generic_name]
      ,[category_id]
      ,[dosage_form]
      ,[strength]
      ,[manufacturer]
      ,[needs_prescription]
      ,[is_who_essential]
      ,[is_active]
      ,[created_at]
  FROM [medlynk_africa].[dbo].[medicines]